# Generated by Django 2.1.7 on 2019-03-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_of_creation', models.DateField()),
                ('date_of_last_update', models.DateField()),
                ('index', models.IntegerField()),
                ('image_details', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'ordering': ['index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_of_creation', models.DateField()),
                ('date_of_last_update', models.DateField()),
                ('index', models.IntegerField()),
                ('text_passage', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'ordering': ['index'],
                'abstract': False,
            },
        ),
    ]
