# Generated by Django 2.1.7 on 2019-04-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('date_of_last_update', models.DateField(auto_now=True)),
                ('index', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='courses.Course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Module')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AlterModelOptions(
            name='imagecomponent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textcomponent',
            options={},
        ),
        migrations.RemoveField(
            model_name='imagecomponent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='imagecomponent',
            name='date_of_creation',
        ),
        migrations.RemoveField(
            model_name='imagecomponent',
            name='date_of_last_update',
        ),
        migrations.RemoveField(
            model_name='imagecomponent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='imagecomponent',
            name='index',
        ),
        migrations.RemoveField(
            model_name='imagecomponent',
            name='module',
        ),
        migrations.RemoveField(
            model_name='imagecomponent',
            name='title',
        ),
        migrations.RemoveField(
            model_name='textcomponent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='textcomponent',
            name='date_of_creation',
        ),
        migrations.RemoveField(
            model_name='textcomponent',
            name='date_of_last_update',
        ),
        migrations.RemoveField(
            model_name='textcomponent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='textcomponent',
            name='index',
        ),
        migrations.RemoveField(
            model_name='textcomponent',
            name='module',
        ),
        migrations.RemoveField(
            model_name='textcomponent',
            name='title',
        ),
        migrations.AddField(
            model_name='imagecomponent',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textcomponent',
            name='component_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Component'),
            preserve_default=False,
        ),
    ]
