# Generated by Django 2.1.7 on 2019-04-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190402_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='instructor',
            new_name='learner',
        ),
    ]
