# Generated by Django 2.1.7 on 2019-04-03 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190403_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='result',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
