# Generated by Django 2.1.7 on 2019-03-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190326_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomponent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagecomponents', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='textcomponent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textcomponents', to='courses.Course'),
        ),
    ]
