# Generated by Django 2.1.7 on 2019-04-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190403_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
        migrations.AddField(
            model_name='instructor',
            name='autobiography',
            field=models.TextField(default=''),
        ),
    ]
