# Generated by Django 2.1.7 on 2019-04-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190403_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={},
        ),
        migrations.RemoveField(
            model_name='component',
            name='index',
        ),
        migrations.AddField(
            model_name='imagecomponent',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
