# Generated by Django 2.1.7 on 2019-04-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_learner_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='course',
        ),
        migrations.AddField(
            model_name='enrolment',
            name='course',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
