# Generated by Django 2.1.7 on 2019-03-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190326_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomponent',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagecomponent',
            name='date_of_last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='textcomponent',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='textcomponent',
            name='date_of_last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
