# Generated by Django 2.1.7 on 2019-04-05 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190405_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cecu_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor'),
            preserve_default=False,
        ),
    ]
