# Generated by Django 2.1.7 on 2019-04-06 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
