# Generated by Django 2.1.7 on 2019-04-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190405_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor_name',
        ),
    ]
