# Generated by Django 2.1.7 on 2019-03-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190326_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='my quiz', max_length=200),
            preserve_default=False,
        ),
    ]
