# Generated by Django 2.1.7 on 2019-04-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190402_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='course',
        ),
        migrations.AddField(
            model_name='enrolment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
