# Generated by Django 2.1.7 on 2019-04-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190406_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='learner',
            old_name='learner',
            new_name='user',
        ),
    ]
