# Generated by Django 2.2 on 2019-04-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190406_0451'),
        ('courses', '0005_auto_20190405_1533'),
    ]

    operations = [
    ]
