# Generated by Django 2.1.7 on 2019-04-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190405_1533'),
        ('courses', '0007_auto_20190406_1007'),
    ]

    operations = [
    ]
