# Generated by Django 2.1.7 on 2019-04-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_learner_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='course',
        ),
    ]
