# Generated by Django 2.1.7 on 2019-04-12 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190407_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='staff_id',
            field=models.CharField(default='11111111', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
