# Generated by Django 2.2 on 2019-04-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_learner_staff_id'),
        ('courses', '0010_component_component_type'),
    ]

    operations = [
    ]
