# Generated by Django 2.1.7 on 2019-04-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_merge_20190417_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='cecu_awarded',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='cecu_value',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
