# Generated by Django 2.2 on 2019-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20190421_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
