# Generated by Django 2.1.7 on 2019-04-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190425_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='num_questions',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
