# Generated by Django 2.1.7 on 2019-04-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190426_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='cecu_awarded',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
