# Generated by Django 2.1.7 on 2019-04-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190426_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='deployed',
            new_name='is_deployed',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='passed',
            new_name='is_passed',
        ),
    ]
